apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'io.gitlab.arturbosch.detekt'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'androidx.room'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    buildToolsVersion = '35'
    compileSdk 35
    defaultConfig {
        applicationId "com.jeffbrandon.recipebinder"
        minSdkVersion 21
        targetSdk 35
        vectorDrawables.useSupportLibrary = true
        def major = 0
        def minor = 0
        def patch = 13
        versionCode major << 16 | minor << 8 | patch
        versionName "$major.$minor.$patch"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        room {
            schemaDirectory "$projectDir/schemas"
        }
    }
    flavorDimensions = ["version"]
    productFlavors {
        alpha {
            dimension "version"
            applicationIdSuffix ".alpha"
        }
        standard {
            dimension "version"
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig true
    }
    buildFeatures.viewBinding = true
    namespace 'com.jeffbrandon.recipebinder'
    lint {
        abortOnError false
    }
}

dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlin_coroutines_version"
    implementation "com.squareup.moshi:moshi:$moshi_version"
    implementation "com.jakewharton.timber:timber:4.7.1"
    implementation "com.google.zxing:core:3.4.1"
    implementation "androidx.room:room-ktx:$room_version"
    implementation "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    ksp "com.squareup.moshi:moshi-kotlin-codegen:$moshi_version"

    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.viewpager2:viewpager2:1.1.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation "androidx.savedstate:savedstate-ktx:1.2.1"

    implementation "com.google.dagger:hilt-android:$hilt_version"
    ksp "com.google.dagger:dagger-compiler:$hilt_version"
    ksp "com.google.dagger:hilt-compiler:$hilt_version"

    implementation "androidx.activity:activity-ktx:1.9.3"
    implementation "androidx.fragment:fragment-ktx:$fragment_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    implementation platform('com.google.firebase:firebase-bom:33.6.0')
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'

    debugImplementation "androidx.fragment:fragment-testing:$fragment_version"

    testImplementation 'junit:junit:4.13.2'
    testImplementation "androidx.arch.core:core-testing:$arch_version"
    testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlin_version"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlin_coroutines_version"
    testImplementation "org.mockito.kotlin:mockito-kotlin:3.1.0"
    androidTestImplementation 'androidx.test:runner:1.6.2'

    detekt("io.gitlab.arturbosch.detekt:detekt-formatting:$detekt_version")
    detekt("io.gitlab.arturbosch.detekt:detekt-cli:$detekt_version")
}
